spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userd
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Pragadees9363260@mac
  jpa:
    hibernate.ddl-auto: update  
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
